### PR TITLE
[fix] remove private from pkg.json

### PR DESCRIPTION
**Pull request by joshuaellis**
delete `private` instead of setting to false to fix merge checks...

### CODE REVIEW

**Comment by joshuaellis** [comment]
@gsimone the sandbox CI breaking all the time was bugging me, but I don't want to just merge the fix without understanding:
* how come the pkg.json for the project has `private:true`?
* what is the CI supposed to actually do?
* Do we want to keep it? not sure how long it's been broken for.

**Comment by drcmda** [comment]
The private flag prevents you from publishing from root, because if you did the release is broken. You can only publish from dist so that end users can import directly without having to include the dist folder. Imo this pr would be kinda dangerous.

**Comment by gsimone** [comment]
Need to change the publishDirectory config for CSB, meant to fix it but life attacked.

**Comment by gsimone** [comment]
Fixed in #230

**Comment by joshuaellis** [comment]
@drcmda  this is why we make PRs to review things 👌🏻 All I saw was an error in the logs.

@gsimone  🙏🏻

**Comment by drcmda** [comment]
> this is why we make PRs to review things 👌🏻 

😅 that must have been a secret hint in there

**Pull request closed without merging**
