### PR TITLE
Add cubemap presets to Environment component

### LINKED ISSUE #202: Environment map presets
Environment maps are a requirement for metallic materials to render properly, so it would be helpful to have a way to quickly pull in a basic environment map without manually downloading a bunch of files and setting up paths.
 
How would you feel about including a set of three.js example cube textures as presets for the environment component? So we could simply say:
```jsx
<Environment preset="pisa" />
```
Here's an example sandbox where I've extended the Environment component with a few presets from Three.js that I'm dynamically loading from jsDelivr:
https://codesandbox.io/s/r3f-environment-helper-lj4jo?file=/src/App.js

### PR DESCRIPTION
**Pull request by mattrossman**
Resolves #202

This includes 9 preset cubmaps from the [Three.js examples](https://github.com/mrdoob/three.js/tree/master/examples/textures/cube). Preset options largely follow the corresponding folder name, though some have been shortened (e.g. "castle" instead of "SwedishRoyalCastle" and "sky" instead of "skyboxsun25deg"). If an invalid preset is provided, the error message will list all valid preset names. `preset` simply re-assigns `path` and `files` at the top of the component, so it will override them if set.

I also added a story for the Environment component that lets you preview the different presets.

⚠️ There seems to be a bug with this story where the environment stops updating after trying out a few presets. Also, the environment disappears if you go to a different story and then come back. This doesn't seem to stem from my modifications, because the component logs the correct values for `files` and `path` on each render. Open to suggestions here.

### CODE REVIEW

**Comment by gsimone** [comment]
Can you consider actually moving the resources to a dedicated repo so that we can add stuff without depending on three? We can always just host on githack or whatever-

**Comment by drcmda** [comment]
this would also allow us to host https://github.com/pmndrs/react-postprocessing/tree/master/examples/src/demos/Bubbles/resources/cube --- as in, a more professional looking minimal studio setup, or https://hdrihaven.com/hdris/

**Comment by mattrossman** [comment]
@gsimone do you want to make that repo under the org, or should I make a personal one?

I like the idea of hosting assets from hdrihaven, those seem cleaner than the assortment of filenames, extensions, and sizes from the Three.js examples. Any suggestions on which ones to use as presets?

Here's a handful I found that represent various lighting situations:

* [studio](https://hdrihaven.com/hdri/?c=studio&h=studio_small_03)
* [sunset](https://hdrihaven.com/hdri/?c=urban&h=venice_sunset)
* [dawn](https://hdrihaven.com/hdri/?c=sunrise-sunset&h=kiara_1_dawn)
* [night](https://hdrihaven.com/hdri/?c=night&h=dikhololo_night)
* [sunny](https://hdrihaven.com/hdri/?c=sunrise-sunset&h=rooitou_park)
* [cloudy](https://hdrihaven.com/hdri/?c=outdoor&h=immenstadter_horn)
* [forest](https://hdrihaven.com/hdri/?c=outdoor&h=forest_slope)
* [alley](https://hdrihaven.com/hdri/?c=urban&h=stone_alley_03)
* [warehouse](https://hdrihaven.com/hdri/?c=indoor&h=empty_warehouse_01)
* [apartment](https://hdrihaven.com/hdri/?c=indoor&h=lebombo)
* [lobby](https://hdrihaven.com/hdri/?c=artificial%20light&h=st_fagans_interior)

**Comment by gsimone** [comment]
Make it on your personal, we will eventually just move all these assets to a pmndrs repo, just for maintanability - maybe just give a few people (me, paul, etc) access to the repo so we can add stuff.

**Comment by mattrossman** [comment]
Sorry for the delay, just added 10 assorted HDRIs to a personal repo and updated the paths for this PR. Switched the CDN to GitHack to be consistent with the existing codebase.

**Comment by gsimone** [comment]
LGTM!

**Pull request merged**
