### PR TITLE
chore: spriteanimator storybook

### PR DESCRIPTION
**Pull request by netgfx**
### Why

For better spriteanimator documentation

### What

Added storybook story for sprite animator

### Checklist

- [ x] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))
- [ x] Storybook entry added ([example](https://github.com/pmndrs/drei/blob/master/.storybook/stories/Example.stories.tsx))
- [ x] Ready to be merged

### CODE REVIEW

**Comment by abernier** [comment]
@netgfx I've checked on the deployed sb: https://drei-gtpkiiyjt-pmndrs.vercel.app/?path=%2Fdocs%2Fmisc-spriteanimator--docs -- seems broken, can you check?

**Comment by netgfx** [comment]
@abernier it seems it can't load the assets needed, I placed them in `/public` folder

**Comment by abernier** [comment]
you should place your sb assets to https://github.com/pmndrs/drei/tree/master/.storybook/public

you can mimic other stories

**Comment by netgfx** [comment]
@abernier yes sorry I had forgotten to commit them, it should be ok now.

**Comment by abernier** [comment]
> @abernier yes sorry I had forgotten to commit them, it should be ok now.

you can also test yourself locally by `yarn build-storybook && npx -y serve storybook-static/`

**Comment by netgfx** [comment]
Ah thanks I'll use it next time, appreciate the help!

Will you merge or should I?

**Comment by abernier** [comment]
I'd like to code-review your story, to deal better with args

**Comment by abernier** [comment]
done in https://github.com/pmndrs/drei/pull/2148/commits/f421b5bb80900b0ae2b8c4babdaaa0e5dc0b5dd2

**Comment by abernier** [comment]
I've also notice you use `any` many times in your source-code which disables TS

**Pull request merged**
