### PR TITLE
fix: set return type to null as a fn w/ return type 'void' is not a valid JSX element

### PR DESCRIPTION
**Pull request by rajput-hemant**
### Checklist

- [ ] Documentation updated
- [ ] Storybook entry added
- [x] Ready to be merged

### CODE REVIEW

**Comment by drcmda** [comment]
it's strange because undefined is an allowed return type.

**Comment by rajput-hemant** [comment]
@drcmda

**Comment by drcmda** [comment]
that issue, TS is so weird sometimes. could you quickly remove the semicolon? then let's merge.

**Comment by rajput-hemant** [comment]
@drcmda done 😇

**Pull request merged**
