### PR TITLE
R3f v6 updates

### PR DESCRIPTION
**Pull request by joshuaellis**
### Why

r3f is upgrading to v6 with it, some breaking changes.

### What

* Transformed calls to `useThree` to use a selector - `const camera = useThree(state => state.camera)`
* Removed usage of `useUpdate`
* add `// @ts-expect-error` in `useCamera` for passing `Raycaster` specifically to r3f `applyProps`
* remove arg `type` from useAspect (it was unused)

TODO
- [x] remove `useEffectfulState`
- [x] check that types are correctly exported in the next alpha of r3f.

### Checklist

- [x] Documentation updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by joshuaellis** [comment]
@gsimone give me a thumb if you're happy or leave me a comment if you're not ⭐

**Comment by gsimone** [comment]
I think some stories are giving errors:

https://drei-n7qt06mvn-pmndrs.vercel.app/?path=/story/misc-usecamera--use-camera-st
https://drei-n7qt06mvn-pmndrs.vercel.app/?path=/story/abstractions-line--basic-line
https://drei-n7qt06mvn-pmndrs.vercel.app/?path=/story/modifiers-useedgesplit--use-edge-split-scene-st

And I might be missing some

**Comment by joshuaellis** [comment]
Ah, it’s annoying that the build process doesn’t pick these up. I’ll check em out, thanks.

**Comment by joshuaellis** [comment]
These are errors with `three-stdlib` and maybe `react-three-fiber@v6`. I'll look at those libraries respectively.

**Comment by drcmda** [comment]
> I think some stories are giving errors:
> 
> https://drei-n7qt06mvn-pmndrs.vercel.app/?path=/story/misc-usecamera--use-camera-st
> https://drei-n7qt06mvn-pmndrs.vercel.app/?path=/story/abstractions-line--basic-line
> https://drei-n7qt06mvn-pmndrs.vercel.app/?path=/story/modifiers-useedgesplit--use-edge-split-scene-st
> 
> And I might be missing some

looking at these now. one is already fixed.

**Comment by joshuaellis** [comment]
Just so we're aware, I know TransformControls is broke & I'm currently fixing it now, but its a beast, so check back soon. I think Paul is adding some new features too ⭐

**Comment by joshuaellis** [comment]
Okay we're all good now all stories work 🤓 great team work, into the beta it goes!

**Pull request merged**
