### PR TITLE
feat: PivotControls scaling

### PR DESCRIPTION
**Pull request by STINGNAILS**
### Why

[Issue 1046](https://github.com/pmndrs/drei/issues/1046)

### What

Added scaling spheres to the PivotControls

### Checklist

- [ ] Link codesandbox
- [ ] Documentation updated
- [ ] Storybook entry added
- [x] Ready to be merged

### CODE REVIEW

**Comment by skypu3** [comment]
does it merge into master ?

**Comment by AdamLeBlanc** [comment]
Hey, this is really useful and exactly what I need for something I am working on. Any idea when/if this will be released on the main branch?

**Comment by cyango** [comment]
the scale deforms the pivot controls

image

Is this fixable?

**Comment by abhirakshit** [comment]
Hello, just checking on the eta for this feature on the main branch.
Thanks

**Comment by mjlever1991** [comment]
Hi just wondering when this is gonna be merged, thanks.

**Comment by mbxxr** [comment]
+1

**Comment by cyango** [comment]
+1

**Comment by STINGNAILS** [comment]
Ok, will check into the mentioned issue with deforming within a week and ask for merging it, sorry for the delay...

**Comment by mjlever1991** [comment]
Great. How do we use this? Does it need to be merged with main Drei branch or is there another way to use this?

**Comment by cyango** [comment]
> Great. How do we use this? Does it need to be merged with main Drei branch or is there another way to use this?

Same question :)

**Comment by mbxxr** [comment]
Excited to push a project forward with this, any idea when we can expect it to be merged?

**Pull request merged**
