### PR TITLE
feat: remove useTesselation, useSimplification and useEdgeSplit 

### LINKED ISSUE #578: RFC: Remove useTesselation, useSimplification and useEdgeSplit
I originally added them, I was going through some of the stories and found a lot of bugs with the implementations, but that's not even the problem.

I'd rather remove these and note promote bad patterns, the best thing for this modifiers would be to just imperatively apply them to the meshes or build custom hooks if they somehow need to be dynamic.

I'm opening an RFC for this since it would require a major, let me know if there are objections.

Another important point is that these rarely are applied more than once on a geometry, so it's a waste of code to have an abstraction where you can just make it in two lines of code 😓

### PR DESCRIPTION
**Pull request by bjornstar**
### Why

resolves #578

### What

BREAKING CHANGES: removes some hooks

### Checklist

- [x] Documentation updated
- [x] Storybooks updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by gsimone** [comment]
Would you mind only doing the removal in this PR and move the eslint stuff to another one? Otherwise, LGTM

**Comment by bjornstar** [comment]
> Would you mind only doing the removal in this PR and move the eslint stuff to another one? Otherwise, LGTM

Sure, done.

**Review by gsimone — APPROVED** [review]

**Comment by gsimone** [comment]
@bjornstar I removed the BREAKING CHANGES tag, we are going to sneak this into the v8 release. Please fix the one merge conflict and ping me so I can merge this, thank you 👐

**Comment by bjornstar** [comment]
No problem, I'll get right on it.

**Comment by bjornstar** [comment]
Ready to go 🚀

**Pull request merged**
