### PR TITLE
[BREAKING CHANGES] – Update three.js from v0.128.0 to v0.134.0 (v8)

### LINKED ISSUE #553: TypeScript type error for MeshDistortMaterial
- `three` version: 0.132.2
- `@react-three/fiber` version: 7.0.7
- `@react-three/drei` version: 7.11.0
- `node` version: 16.9.1
- `npm` version: 6.14.14

### Problem description:

`MeshDistortMaterial` has an incorrect typing and nothing in TypeScript will satisfy it:

image

### Relevant code:
The offending definition in `MeshDistortMaterial.d.ts`:

```ts
export declare const MeshDistortMaterial: React.ForwardRefExoticComponent<Pick<Omit<import("@react-three/fiber").Node<MeshPhysicalMaterial, [MeshPhysicalMaterialParameters]>, "color" | undefined> & {
    color?: import("@react-three/fiber").Color | undefined;
} & {
    time?: number | undefined;
    distort?: number | undefined;
    radius?: number | undefined;
} & {
    speed?: number | undefined;
    factor?: number | undefined;
}, "visible" | "attach" | "attachArray" | "attachObject" | "args" | "children" | "key" | "onUpdate" | "dispose" | "type" | "id" | "uuid" | "name" | "userData" | "toJSON" | "clone" | "copy" | "addEventListener" | "hasEventListener" | "removeEventListener" | "dispatchEvent" | "color" | "map" | "time" | "transparent" | "fog" | "opacity" | "speed" | "alphaTest" | "alphaToCoverage" | "blendDst" | "blendDstAlpha" | "blendEquation" | "blendEquationAlpha" | "blending" | "blendSrc" | "blendSrcAlpha" | "clipIntersection" | "clippingPlanes" | "clipShadows" | "colorWrite" | "defines" | "depthFunc" | "depthTest" | "depthWrite" | "stencilWrite" | "stencilFunc" | "stencilRef" | "stencilWriteMask" | "stencilFuncMask" | "stencilFail" | "stencilZFail" | "stencilZPass" | "isMaterial" | "needsUpdate" | "polygonOffset" | "polygonOffsetFactor" | "polygonOffsetUnits" | "precision" | "premultipliedAlpha" | "dithering" | "side" | "shadowSide" | "toneMapped" | "vertexColors" | "version" | "onBeforeCompile" | "customProgramCacheKey" | "setValues" | "roughness" | "metalness" | "lightMap" | "lightMapIntensity" | "aoMap" | "aoMapIntensity" | "emissive" | "emissiveIntensity" | "emissiveMap" | "bumpMap" | "bumpScale" | "normalMap" | "normalMapType" | "normalScale" | "displacementMap" | "displacementScale" | "displacementBias" | "roughnessMap" | "metalnessMap" | "alphaMap" | "envMap" | "envMapIntensity" | "refractionRatio" | "wireframe" | "wireframeLinewidth" | "wireframeLinecap" | "wireframeLinejoin" | "skinning" | "vertexTangents" | "morphTargets" | "morphNormals" | "flatShading" | "isMeshStandardMaterial" | "reflectivity" | "clearcoat" | "clearcoatMap" | "clearcoatRoughness" | "clearcoatRoughnessMap" | "clearcoatNormalScale" | "clearcoatNormalMap" | "ior" | "sheen" | "transmission" | "transmissionMap" | "radius" | "distort" | "factor"> & React.RefAttributes<unknown>>;
export {};
```

### Suggested solution:
This can be fixed by changing the comma separating the last part of the type definition (starting before `"visible"`) to an ampersand:

```ts
export declare const MeshDistortMaterial: React.ForwardRefExoticComponent<Pick<Omit<import("@react-three/fiber").Node<MeshPhysicalMaterial, [MeshPhysicalMaterialParameters]>, "color" | undefined> & {
    color?: import("@react-three/fiber").Color | undefined;
} & {
    time?: number | undefined;
    distort?: number | undefined;
    radius?: number | undefined;
} & {
    speed?: number | undefined;
    factor?: number | undefined;
} & "visible" | "attach" | "attachArray" | "attachObject" | "args" | "children" | "key" | "onUpdate" | "dispose" | "type" | "id" | "uuid" | "name" | "userData" | "toJSON" | "clone" | "copy" | "addEventListener" | "hasEventListener" | "removeEventListener" | "dispatchEvent" | "color" | "map" | "time" | "transparent" | "fog" | "opacity" | "speed" | "alphaTest" | "alphaToCoverage" | "blendDst" | "blendDstAlpha" | "blendEquation" | "blendEquationAlpha" | "blending" | "blendSrc" | "blendSrcAlpha" | "clipIntersection" | "clippingPlanes" | "clipShadows" | "colorWrite" | "defines" | "depthFunc" | "depthTest" | "depthWrite" | "stencilWrite" | "stencilFunc" | "stencilRef" | "stencilWriteMask" | "stencilFuncMask" | "stencilFail" | "stencilZFail" | "stencilZPass" | "isMaterial" | "needsUpdate" | "polygonOffset" | "polygonOffsetFactor" | "polygonOffsetUnits" | "precision" | "premultipliedAlpha" | "dithering" | "side" | "shadowSide" | "toneMapped" | "vertexColors" | "version" | "onBeforeCompile" | "customProgramCacheKey" | "setValues" | "roughness" | "metalness" | "lightMap" | "lightMapIntensity" | "aoMap" | "aoMapIntensity" | "emissive" | "emissiveIntensity" | "emissiveMap" | "bumpMap" | "bumpScale" | "normalMap" | "normalMapType" | "normalScale" | "displacementMap" | "displacementScale" | "displacementBias" | "roughnessMap" | "metalnessMap" | "alphaMap" | "envMap" | "envMapIntensity" | "refractionRatio" | "wireframe" | "wireframeLinewidth" | "wireframeLinecap" | "wireframeLinejoin" | "skinning" | "vertexTangents" | "morphTargets" | "morphNormals" | "flatShading" | "isMeshStandardMaterial" | "reflectivity" | "clearcoat" | "clearcoatMap" | "clearcoatRoughness" | "clearcoatRoughnessMap" | "clearcoatNormalScale" | "clearcoatNormalMap" | "ior" | "sheen" | "transmission" | "transmissionMap" | "radius" | "distort" | "factor"> & React.RefAttributes<unknown>>;
export {};
```

### PR DESCRIPTION
**Pull request by bjornstar**
(by @bjornstar & @joshuaellis)

### Why

`three.js` `v0.134.0` has been out for a few weeks now -- https://github.com/mrdoob/three.js/releases/tag/r134

### What

- There was a deprecated shape that I removed (see https://github.com/mrdoob/three.js/pull/22559), if you want to continue using it, we can import it from the examples
- There was one small type issue that I resolved by converting to Instanced versions
- Fixes #553 

### Checklist

- [x] Ready to be merged

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
This would be a breaking change because everyone would not be able to use the latest version of `drei` without updating their version of `three` no? This makes me hesitant. 

If we were to release a breaking change this would be an opportunity to change `three-stdlib` from a dep to a peer-dep...

**Comment by bjornstar** [comment]
> This would be a breaking change because everyone would not be able to use the latest version of `drei` without updating their version of `three` no? This makes me hesitant.

We are not able to use `drei` with the latest version of `three` without workarounds because of #553. The types baked into `drei` are broken.

> If we were to release a breaking change this would be an opportunity to change `three-stdlib` from a dep to a peer-dep...

Are you saying you want me to make `three-stdlib` a `peerDependency` and add it to this PR?

**Comment by bjornstar** [comment]
Hmm, I should probably update the peerDependency version for `three` as well.

Personally, I don't think it's that big of a deal upgrading which version of `three` I'm using. There's lots of great stuff coming out all the time and they're generally pretty good about not breaking existing things.

Have you given more thought to making `three-stdlib` a peerDependency?

**Comment by joshuaellis** [comment]
This PR would be a breaking change so lets also move `three-stdlib` to be a peer dependancy too. Also I think @drcmda made a depreciation notice in one of the components, so we could remove that too.

**Comment by bjornstar** [comment]
> This PR would be a breaking change so lets also move `three-stdlib` to be a peer dependancy too. Also I think @drcmda made a depreciation notice in one of the components, so we could remove that too.

The DepthBuffer that is deprecated is used in the SpotLight storybook, should I remove that as well?

**Comment by bjornstar** [comment]
> > This PR would be a breaking change so lets also move `three-stdlib` to be a peer dependancy too. Also I think @drcmda made a depreciation notice in one of the components, so we could remove that too.
> 
> The DepthBuffer that is deprecated is used in the SpotLight storybook, should I remove that as well?

I can see useDepthBuffer is the drop in replacement for DepthBuffer so I'll update the storybook to use that.

**Comment by bjornstar** [comment]
OK, I cleaned up my commits and addressed all the issues. Please take a look.

**Comment by bjornstar** [comment]
The last bit of the puzzle is the Parametric geometry, do we want to drop support for that and remove the storybook entry?

**Comment by joshuaellis** [comment]
>The last bit of the puzzle is the Parametric geometry, do we want to drop support for that and remove the storybook entry?

Wasn't that removed recently?

**Comment by joshuaellis** [comment]
We'll probably need to update the readme to reflect these changes too actually.

**Comment by bjornstar** [comment]
> We'll probably need to update the readme to reflect these changes too actually.

Dropped the storybook and removed parametric support from the README.

**Review by joshuaellis — APPROVED** [review]
Amazing. I'm gonna bump some other deps too now and push an addition

**Comment by joshuaellis** [comment]
@bjornstar there's a few tiny tidy ups I want to do for this release, so i'll do them later 😄

**Comment by drcmda** [comment]
are we sure about the peer dep? imo it's not something the use should care much about, and wouldn't that make it a mess for them to align drei with std? drei pulls features out of std that may or may not exist yet, and it will crash if users update it without updating std. yes it's a convenience for us and it saves us some chores - but do users really benefit? i also think that this will, once again, crash the entire eco system, every react+three app out there will fail, and im not sure if the change is worth it.

**Comment by joshuaellis** [comment]
>imo it's not something the user should care much about, it's an implementation detail. and wouldn't that make it a mess for them to align drei with std? drei pulls features out of std that may or may not exist yet, and it will crash if users update it without updating std. knowing which drei fits which std seems like guesswork then? yes it's a convenience for us and it saves us some chores - but do users really benefit? i also think that this will, once again, crash the entire eco system, every react+three app out there will fail, and im not sure if the change is worth that

Completely disagree, i'm so sick of releasing a bump for no reason than to fix a bug in another package. It's an incredible burden and unnecessary to do so when peer-deps is available.

> last but not least, if we introduce a major breaking change like that, i would wait for react 18 and r3f v8. otherwise it's going to be two breaking changes just 2 months apart. r18 and v8 will also bring some other changes, like use-asset -> suspend. we could move it to this branch as well.

I don't think we should be holding back on fixing issues over another library.

**Comment by bjornstar** [comment]
My goal with this PR was to update the types for `three` that are baked into this package so that `racing-game` can upgrade to the latest version of `three`. It's turned into a bit of an ordeal with unrelated changes rolled in.

Personally, as a user I like having explicit dependencies and don't like dealing with the extra burden of discovering that my dependencies don't include their own dependencies and I have to supply them. All three popular package managers dedupe dependencies pretty well now so peerDependencies don't seem to be much of an improvement in that regard.

I feel like our goal should be to support the latest version of a library in a reasonable timeframe after its release. Otherwise it feels like we are holding back the community. If more help is needed to maintain the library, I'd be happy to help out. I don't feel like pulling in bug fixes from other libraries is burdensome or unnecessary.

I'd be happy to chat more about it on discord if you feel that would help.

**Comment by bjornstar** [comment]
@joshuaellis Sorry I lost your changes when I rebased. I'll put them into separate PRs.

**Comment by bjornstar** [comment]
I've dropped the controversial `three-stdlib` change. This PR is now just a bump of `three.js` can we reconsider merging it?

**Comment by drcmda** [comment]
sure!

btw, i have breaking changes in r3f v8, specifically everything that has to do with attach, which drei uses a lot. this will take a hard major.

**Pull request merged**
