### PR TITLE
chore: migrate storybooks to use controls instead of knobs

### LINKED ISSUE #685: [dev warnings] storybook peer dependencies
### Problem description:

When running `yarn` we are presented with several warnings:

```
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/api > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/api@^6.3.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/components@^6.3.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/core-events@^6.3.0".
```

### Suggested solution:

- Update storybook related dependencies

### PR DESCRIPTION
**Pull request by bjornstar**
### Why

When updating the storybook dependencies for #685 I noticed that knobs is being deprecated in v7. I started migrating the storybooks, but it started getting to be quite a big change so I'll start with these. There are 21 more storybooks to migrate.

### What

-  Updated all `@storybook/components` to the latest version: `v6.4.9`
- Fixes #685
- Added a missing hook dep: `faces` for GizmoViewcube

Migrated these storybooks away from knobs
- Billboard
- CameraShake
- Cloud
- Environment
- FirstPersonControls
- FlyControls
- GizmoHelper

### Checklist

- [x] Documentation updated
- [x] Storybook entry added
- [x] Ready to be merged

### CODE REVIEW

**Comment by gsimone** [comment]
Don't know if saw this, might be useful https://github.com/pmndrs/drei/pull/282

**Comment by bjornstar** [comment]
> Don't know if saw this, might be useful #282

Ah, thanks for the heads up. I'm doing it a little bit differently but it's good to see how others are doing it.

**Comment by bjornstar** [comment]
Branch has been updated, can we take these initial storybooks first?

**Review by joshuaellis — APPROVED** [review]
I'm happy with the gradual impl.

**Comment by bjornstar** [comment]
Does someone want to merge this? Or is there more that you'd like me to do here?

**Comment by gsimone** [comment]
@bjornstar done ✅

**Pull request merged**
