### PR TITLE
Issue #127: Add a custom material story for Text

### LINKED ISSUE #127: Chore: Add a custom material story for Text

### PR DESCRIPTION
**Pull request by johnmarinelli**
Closes #127

### CODE REVIEW

**Comment by gsimone** [comment]
Would you mind actually making two separate stories? one default and one custom material - should be just come copypasting

**Comment by johnmarinelli** [comment]
@gsimone sure, no worries - see newest commit

**Comment by gsimone** [comment]
Hey John, really sorry for the super late reply, I'm going through all existing PRs and merging, could you look at fixing the conflicts? I think they exist because outline was added to text.

@johnmarinelli

**Comment by johnmarinelli** [comment]
@gsimone no worries :) i'll take a look

**Pull request merged**
