### PR TITLE
Update Draco decoders path

### PR DESCRIPTION
**Pull request by clementroche**
Use the latest Draco version
https://github.com/google/draco/releases/tag/1.5.5

### CODE REVIEW

**Comment by drcmda** [comment]
did you try it, can you confirm it work? the old version was deliberate because draco had breaking changes in patch versions.

**Comment by clementroche** [comment]
Can you link where the discussion happened, i was not aware ? @drcmda

**Comment by drcmda** [comment]
here is one, we used draco indiscriminately without pinning back then https://github.com/pmndrs/drei/issues/189

we could also ping @donmccurdy, don, do you think 1.5.x is safe with current threejs?

**Comment by donmccurdy** [comment]
I'm not aware of breaking API changes — there were some problems with the Draco CDN during release rollouts, but I think those were accidental. This is a newer version of the Draco API than three.js is using, so I haven't tested it, but would expect that if it seems to be working fine in your tests then it should be OK.

**Comment by drcmda** [comment]
thanks! in that case, everything's working fine, tested it against local binaries and remote.

**Comment by donmccurdy** [comment]
Will upgrade three.js in next release:

- https://github.com/mrdoob/three.js/pull/25475

We're updating DRACOLoader to use newer Draco APIs there, but previous versions of DRACOLoader work with the newest Draco library too.

**Pull request merged**
