### PR TITLE
[RC] v3.0.0

### LINKED ISSUE #181: Adding points in Line
Hi, firstly thanks for the project!

I am trying to draw a line with width where the path changes based on state. The number of points to be drawn can increase or decrease as state changes.

It seems that the geometry in `Line` is not updated when the number of points change. I realise this might be related to the way three works and might be desirable from a performance perspective, but if I use the basic r3f `line` element, the line is updated (presumably by re-creating the geometry) as points are added.

I tried hacking around with `onUpdate`, similar to how it works with `line`, but it didn't work.

I created codesandbox showing the issue: https://codesandbox.io/s/r3f-line-adding-points-y7utc?file=/src/index.js

The `Line` is created with 5 points initially, so you can add up to five points with the Add Point button, but after that new points don't appear.

Any help/workaround much appreciated!

### LINKED ISSUE #221: react-native exports causing crashes because of internal imports
## What
There are currently three issues relating to imports in `react-native`
* #212 
* #182
* #19

## Why
This [comment](https://github.com/pmndrs/drei/issues/19#issuecomment-733558823) highlights the issue – `Html` and `Loader` components because they use either `react-dom` or `react-spring/web`. 

## Solution (potential)
Have an ad-hoc exporter for native, kind of like `react-spring` where `Html` would not be included. We *could* create a `react-native` version of `Loader` if we want.

### LINKED ISSUE #233: Blob is not defined (nextjs - ssr)
- `three` version: 124
- `react-three-fiber` version: 5.3.12
- `@react-three/drei` version: 2.2.16

### Problem description:

with the new update I can see `Cloud.tsx` imports `CloudImage` which at some point calls `new Blob` I don't think `Blob` is defined in `node`.

### Suggested solution:

we could use `cross-blob` which is probably like `isomorphic-fetch`. Alt we can look at other ways that mean we don't need to use another library.

### LINKED ISSUE #238: Make <Environment /> work with a passed scene
When using a non-default scene, environment doesn't work. It's enough to add a `scene` prop:

```jsx
<Environment scene={myScene} />
```

This is a two-three lines change max

## TODO

- [ ] Make the change
- [ ] Add this case to the storybook

### LINKED ISSUE #241: Support EXT_meshopt_compression in useGLTF
### Describe the feature you'd like:

I'd like to support the `EXT_meshopt_compression` glTF extension in the `useGLTF` hook, which enables further file compression beyond what Draco can achieve. See: https://www.npmjs.com/package/gltfpack

For example, with Draco alone I can shrink a 600 KB model down to 430 KB. With `gltfpack` using the `-c` flag I can shrink it all the way down to **130 KB**.

### Suggested implementation:

Supporting this involves:
```js
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module'

// In the draco function
loader.setMeshoptDecoder(MeshoptDecoder)
```

I'm not sure if there's any disadvantage to always leaving this on, but if needed we could add another parameter after the draco path to allow users to customize the behavior.

### LINKED ISSUE #242: In softShadows the `frustum` attribute is being called `frustrum`
We should probably just alias it to the correct name

### PR DESCRIPTION
**Pull request by joshuaellis**
### Why

* resolves #242
* resolves #241 
* resolves #238 
* resolves #233 
* resolves #221 
* resolves #181 

### What

BREAKING CHANGES: we've had an internal refactor for #221, minimum supported `three` is 125

FEATURES: updated dependencies such as `troika-three-text`, added new props to components.

FIXES: Fixed spelling error & solved nextjs `blob is not defined error`

### Checklist

- [x] Documentation updated
- [x] Storybook entry added
- [x] Ready to be merged

### Things we want to do before release 

- [ ] Move documentation around
- [ ] Cleanup readme
- [ ] Update logo
- [x] Deprecate the `drei` package
- [x] Automate npm release
- [x] Min three version - 125 (add to peer deps)
- [x] Add Reflector component

### CODE REVIEW

**Comment by joshuaellis** [comment]
@drcmda How were you imagining we'd move the documentation to the site? I don't mind shuffling all that around.
@gsimone i'd like to leave the logo sorting to you 👌🏼

**Comment by joshuaellis** [comment]
> Automate npm release

Isn't this already done with tagging? Or did you want to use something like `semantic-release`?

**Comment by gsimone** [comment]
> > Automate npm release
> 
> Isn't this already done with tagging? Or did you want to use something like `semantic-release`?

it's not automated though

**Comment by joshuaellis** [comment]
semantic-release can be automated with a github [action](https://github.com/cycjimmy/semantic-release-action). But then you have to do a form of semantic commiting, I think you can still deploy manually if you want?

**Comment by joshuaellis** [comment]
@gsimone docs plan is to move it to the docs work on the pmdrs site, do you think that's achievable? If you invite me as a maintainer I can help move over & help finish anything to get it ready?

**Comment by gsimone** [comment]
@joshuaellis I can copypaste the README in the new docs, but some elements are still missing (for example the index table)

I'll give it a shot this evening

**Comment by joshuaellis** [comment]
Sounds great, if you need any support @gsimone shout out.

**Pull request merged**
