### PR TITLE
feat(reflector): adds debug prop and improves depth blurring

### LINKED ISSUE #293: Reflector tweaks
https://codesandbox.io/s/busy-wood-2sk0p?file=/src/App.js

(I'm creating this issue just to track & get csb)

### PR DESCRIPTION
**Pull request by emmelleppi**
### Why
the previous reflector added the depth texture to the shader but the fading of the reflection in function of the depth was not perceptible

- [x] Documentation updated
- [x] Storybook entry added
- [x] Ready to be merged

Closes #293

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
Can we tackle issue #277 in this PR, please? Unless you've already done it and I'm being silly.

**Comment by emmelleppi** [comment]
> Can we tackle issue #277 in this PR, please? Unless you've already done it and I'm being silly.
@gsimone is the example I put in the storybook okay or were you thinking of something different (adding tweaks, multiple stories, etc.)?

**Review by joshuaellis — APPROVED** [review]

**Comment by gsimone** [comment]
Gonna merge when Marco is ready with the demo ✌️

**Comment by joshuaellis** [comment]
> Gonna merge when Marco is ready with the demo

I'll leave this for you to merge.

**Comment by emmelleppi** [comment]
> Gonna merge when Marco is ready with the demo ✌️

New reflector: https://codesandbox.io/s/frosty-reflector-23xxw
Old reflector: https://codesandbox.io/s/frosty-reflector-old-version-uox4t

I have also added various combinations in the storybook

**Pull request merged**
