### PR TITLE
fix: Makes Loader go from 0 to 100 instead of 0 to 1

### PR DESCRIPTION
**Pull request by gsimone**
Come on.

### CODE REVIEW

**Comment by joshuaellis** [comment]
It's funny, I saw this all last week, and told myself "I must fix it" and I never did, what would we do without you?

**Comment by gsimone** [comment]
Thankfully I'm here, to fix the stuff that REALLY matters, like this U_U

**Comment by joshuaellis** [comment]
Do you think we still need Travis? I'm not actually clear on what it does.

**Comment by RenaudRohlinger** [comment]
@joshuaellis @gsimone This one makes me remember of one bug. When we want to load something new, the loader assets will stack because we use the same instance of LoadingManager. So it means for example it will do 0 -> 1 on the first load. Then 0.5 -> 1 etc.... because this one is never reset :
https://github.com/mrdoob/three.js/blob/master/src/loaders/LoadingManager.js#L6

So I guess we should use LoadingManager instead of DefaultLoadingManager like this :
https://github.com/RenaudRohlinger/drei/blob/master/src/core/useProgress.tsx
(I don't want to PR yet because I can't test yet but it should work)

**Comment by joshuaellis** [comment]
Are you talking about if there are multiple suspense wrappers in an app?

**Comment by gsimone** [comment]
Makes sense to use multiple Loaders, since this component is intended to "hide" the whole app - so it implies that it's only ever used one at a time

**Comment by joshuaellis** [comment]
Can we write that in the docs then, please? I know it's a bit trivial, I do remember someone having an issue with that, and I did have a similar scenario myself and was confused about what was going on till I really thought about it 👀

**Review by drcmda — APPROVED** [review]

**Pull request merged**
