### PR TITLE
fix: avoid creating new Buffer Geometry

### PR DESCRIPTION
**Pull request by Gusted**
### Why

So, geometry variable will be overridden anyway.

### What

Removing the `let geometry = new THREE.BufferGeometry()` and replace it by the next variable declaration seems to be working and avoiding to create more unnecessary BufferGeometry's.

### Checklist

- [x] Ready to be merged

### CODE REVIEW

**Comment by Gusted** [comment]
@joshuaellis this the correct commit message, right?

**Comment by drcmda** [comment]
Didn't clone also create new buffergeom?

**Comment by Gusted** [comment]
> Doesnt clone also create new buffergeom?

It does. This PR is rather to avoid having an even extra creation of buffer geometry. 
But the clone seems necessary in my eyes, as not cloning somehow caused errors. But I can work around that issues. Let me fix that.

**Comment by joshuaellis** [comment]
They all look good now @Gusted unless i've missed something? 

Also yes, this message is the correct format, but typically the maintainer can change it before hand anyway, so no stress 👍🏼

**Comment by Gusted** [comment]
> They all look good now @Gusted unless i've missed something?

Yep, they look good. No extra buffer geometries are created now on the 3 functions.

**Review by joshuaellis — APPROVED** [review]
🚀

**Pull request merged**
