### PR TITLE
fix: interop Zustand for CJS

### LINKED ISSUE #1544: When building a Next.js 13 project using version 9.77.7, an error occurs
- `three` version:
- `@react-three/fiber` version:
- `@react-three/drei` version: 9.77.7
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:
When building a Next.js 13 project using version 9.77.7, an error occurs :

image

### Suggested solution:
I had to downgrade the version to 9.56.25 in order to successfully build. Please fix it in version 9.77.7.

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #1544.

### CODE REVIEW

**Comment by timoisalive** [comment]
Hey, not sure if this is the reason but I just started getting:

```
Uncaught TypeError: create is not a function
    at ./node_modules/@react-three/drei/core/useProgress.js
```
in my project which has
```
    "@react-three/drei": "^9.68.6",
    "zustand": "^4.3.8"
```

**Comment by CodyJasonBennett** [comment]
Can you share that project? The `^` symbol makes that info impossible to debug from, since it can resolve any version, and your package manager may incorrectly resolve versions outside our control.

**Comment by caioaamaral** [comment]
@CodyJasonBennett Had the same problem, using ` "@react-three/drei": "https://pkg.csb.dev/pmndrs/drei/commit/56656e4d/@react-three/drei"` fixed for me

for instance, I was at "^9.77.8"

**Comment by jglee96** [comment]
[codesandbox](https://codesandbox.io/p/github/jglee96/drei-vitest/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljhbcupx000b356omelcu87i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljhbcupx000d356ohoimfqbf%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljiqrayb00i5356o6np1kygh%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljiqrayb00i4356oidvfqpjc%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljhbcupx000b356omelcu87i%2522%253A%257B%2522id%2522%253A%2522cljhbcupx000b356omelcu87i%2522%252C%2522activeTabId%2522%253A%2522cljiu1ho40059356odw9ptky9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljhbcupx000a356oy82n7g8n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FTarget.tsx%2522%252C%2522id%2522%253A%2522cljiu1ho40059356odw9ptky9%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljiqrayb00i5356o6np1kygh%2522%253A%257B%2522id%2522%253A%2522cljiqrayb00i5356o6np1kygh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljhbcupx000c356ofayvy7v7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljiqr5ou00av356opx7gdj6j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljhbcupx000c356ofayvy7v7%2522%257D%252C%2522cljiqrayb00i4356oidvfqpjc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljiqrayb00i3356oi2pyonb7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljiqrcas0011fned2q0248l3%2522%257D%255D%252C%2522id%2522%253A%2522cljiqrayb00i4356oidvfqpjc%2522%252C%2522activeTabId%2522%253A%2522cljiqrayb00i3356oi2pyonb7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

v9.77.8 has same error.
Using "@react-three/drei": "https://pkg.csb.dev/pmndrs/drei/commit/56656e4d/@react-three/drei" works.
However test fail because of `react-merge-refs` cjs, esm things.
image

**Comment by Hasan-446** [comment]
same error on latest version 
image
image
image

**Comment by CodyJasonBennett** [comment]
Should be fixed (for real) in 9.77.9.

**Comment by RhisavRay** [comment]
> same error on latest version image image image

I am facing the exact same issue. By when can we expect a fix? Also where do I get this useProgress.js file?

**Comment by CodyJasonBennett** [comment]
The version after contains a fix. .8 was still a broken build.

**Comment by ruslanvasylev** [comment]
Hey guys, I'm getting the following when trying to run some tests

> Should be fixed (for real) in 9.77.9.

`"@react-three/drei": "9.78.1",`

`    TypeError: i is not a function

      at ../../node_modules/@react-three/drei/index.cjs.js:1:227930`

**Comment by CodyJasonBennett** [comment]
@ruslanvasylev can you share a project and/or try a clean install? I don't see anything wrong since this patch landed.

**Comment by CodyJasonBennett** [comment]
Releasing 9.78.2 in a moment. This had come from a Rollup upgrade which had been breaking our CJS bundle up to this point. We have e2e tests, I'll try to harden them to test this behavior.

**Comment by ruslanvasylev** [comment]
Thank you @CodyJasonBennett; this one seems to pass all tests!

**Comment by RhisavRay** [comment]
I am still getting this error. What to do?
image
image

**Comment by CodyJasonBennett** [comment]
Update to latest Drei with a clean install. If that doesn't work, let me know the version and I can take a look.

**Comment by abernier** [comment]
> Releasing 9.78.2 in a moment. This had come from a Rollup upgrade which had been breaking our CJS bundle up to this point. We have e2e tests, I'll try to harden them to test this behavior.

https://github.com/pmndrs/drei/pull/2202

**Pull request merged**
