### PR TITLE
fix: useTexture callback parameter and behavior

### LINKED ISSUE #1968: `useTexture` onLoad fires incorrectly
- `three` version: 0.164.1
- `@react-three/fiber` version: 8.16.6
- `@react-three/drei` version: 9.105.6
- `node` version: v22.2.0
- `npm` (or `yarn`) version: 1.22.22

### Problem description:

The `onLoad` callback fires every render if the callback isn't memoized, because `useEffect` hook depends on the function instead of the mapped texture data. On the other hand, if the callback is memoized, it will only fire once and then never again, even if the data finishes loading later.

### Relevant code:

```ts
const texture = useTexture(
    'some_texture.jpg',
    () => console.log('every render'),
);
```

Caused by this code in `useTexture`:

```ts
useLayoutEffect(() => {
  onLoad?.(mappedTextures)
}, [onLoad])
```

### Suggested solution:

```ts
useLayoutEffect(() => {
  onLoad?.(mappedTextures)
}, [mappedTextures])
```

I will provide a PR with this change.

### LINKED ISSUE #1969: `useTexture(..., onLoad)` callback receives incorrect values
- `three` version: 0.164.1
- `@react-three/fiber` version: 8.16.6
- `@react-three/drei` version: 9.105.6
- `node` version: v22.2.0
- `npm` (or `yarn`) version: 1.22.22

### Problem description:

The types declare that the callback receives the same type that's returned from the hook itself. However, that's not the case, and it will never receive a record object.

### Relevant code:

```ts
const returnedTextures = useTexture(
    {map: 'color.jpg', normalMap: 'normal.png'},
    (callbackTextures) => {
        // callbackTextures can never be an object here, and always produces and
        // array, as opposed to returnedTextures, which correctly adheres to the
        // declared type.
    },
);
```

### Suggested solution:

Fix the callback to adhere to the declared type. I will provide a PR for this.

### PR DESCRIPTION
**Pull request by jwueller**
### Why

Fixes #1968
Fixes #1969

### What

Fixes the behavior of the `useTexture(..., onLoad)` callback according to the declared types, as well as the conditions under which it is fired (i.e. when the data changes, not when the function does).

### Checklist

- [ ] Documentation updated ([example](https://github.com/pmndrs/drei/blob/master/README.md#example))
- [ ] Storybook entry added ([example](https://github.com/pmndrs/drei/blob/master/.storybook/stories/Example.stories.tsx))
- [x] Ready to be merged

No documentation or storybook change is required, because this just fixes previously-documented behavior.

### CODE REVIEW

**Comment by FarazzShaikh** [comment]
@jwueller Can you please resolve merge conflicts and merge `master` into this? There was a refactor to Drei. Please let me know if youre not able to, we will close this and reopen a new PR on latest `master`

**Comment by clementroche** [comment]
@FarazzShaikh the conflicts resolution is the only blockers?

**Comment by FarazzShaikh** [comment]
@clementroche yes. But the conflicts are extensive. Better to start a new PR with latest upstream

**Comment by clementroche** [comment]
omw @FarazzShaikh

**Comment by clementroche** [comment]
done in https://github.com/pmndrs/drei/pull/2142

**Comment by abernier** [comment]
why another PR for solving conflicts?

**Comment by FarazzShaikh** [comment]
@abernier Yes, this one is duplicate now and should be closed. The last time I checked, there were a lot of conflicts as this PR was made before the refactor.

**Comment by abernier** [comment]
@FarazzShaikh ok closing it 

> @abernier Yes, this one is duplicate now and should be closed. The last time I checked, there were a lot of conflicts as this PR was made before the refactor.

ok, closing as duplicates in favor of https://github.com/pmndrs/drei/pull/2142

**Pull request closed without merging**
